proyectoWWW/apps/empresa/urls.py
from django.conf.urls import url

from .views import *

urlpatterns = [
    url(r"^registrar$", registrar_empresa, name="empresa_registrar_empresa"),
    url(
        r"^modificar/(?P<empresa_id>\d+)$",
        modificar_empresa,
        name="empresa_modificar_empresa",
    ),
    url(
        r"^registrar-solicitud$",
        solicitar_registro_empresa,
        name="empresa_registrar_solicitud_empresa",
    ),
    url(
        r"^registrar-solicitud/(?P<plan_id>\d+)$",
        solicitar_registro_empresa,
        name="empresa_registrar_solicitud_empresa",
    ),
    url(
        r"^listado-solicitudes$",
        listado_solicitudes,
        name="empresa_listado_solicitudes",
    ),
    url(r"^gestionar$", gestionar_empresas, name="empresa_gestionar_empresas_cliente"),
    url(
        r"^gestionar/modificar/(?P<empresa_id>\d+)$",
        gestionar_empresas,
        name="empresa_modificar_empresa_cliente",
    ),
    url(
        r"^copia-seguridad/(?P<empresa_id>\d+)$",
        obtener_copia_seguridad,
        name="empresa_copia_seguridad_empresa",
    ),
    url(
        r"^aceptar-rechazar-solicitud/(?P<id_solicitud>\d+)/(?P<estado_aprobacion>\d+)$",
        aceptar_rechazar_solicitud,
        name="empresa_aceptar_rechazar_solicitud",
    ),
    url(r"^editar-planes$", editar_planes, name="empresa_editar_planes_empresa"),
]

proyectoWWW/apps/tema/urls.py
from django.conf.urls import url
from .views import *

urlpatterns = [
    # Vistas de los temas
    url(r"^registro$", RegistrarTema.as_view(), name="tema_registro_tema"),
    url(
        r"^modificar/(?P<pk>\d+)$", ModificarTema.as_view(), name="tema_modificar_tema"
    ),
    url(r"^eliminar/(?P<id_tema>\d+)$", eliminarTema, name="tema_eliminar_tema"),
]

proyectoWWW/apps/empresa/models.py
from django.core.exceptions import ValidationError
from django.db import models
from django_tenants.models import TenantMixin, DomainMixin

from simple_history.models import HistoricalRecords
from django_tenants.postgresql_backend.base import _is_valid_schema_name

from apps.Usuario.models import Usuario

CHOICES_TEMA = (
    ("a", "Tema A"),
    ("b", "Tema B"),
    ("c", "Tema C"),
    ("d", "Tema D"),
    ("e", "Tema E"),
)

CHOICES_COLOR = (
    ("coffee", "Café"),
    ("dark", "Oscuro"),
    ("dust", "Arena"),
    ("gray", "Gris"),
    ("lime", "Lima"),
    ("mint", "Menta"),
    ("navy", "Azul marino"),
    ("ocean", "Oceano"),
    ("prickly-pear", "Higo"),
    ("purple", "Violeta"),
    ("well-red", "Rojo"),
    ("yellow", "Amarillo"),
)


class Modulo(models.Model):
    nombre = models.CharField(max_length=100)

    @staticmethod
    def crear_modulos_iniciales():
        if Modulo.objects.all().count() == 0:
            Modulo.objects.create(nombre="Actividades")
            Modulo.objects.create(nombre="Calendario")
            Modulo.objects.create(nombre="Eventos")
            Modulo.objects.create(nombre="Noticias")
            Modulo.objects.create(nombre="Participantes")
            Modulo.objects.create(nombre="Reportes")
            Modulo.objects.create(nombre="Temas")
            Modulo.objects.create(nombre="Usuarios")

    def __str__(self):
        return self.nombre


class Plan(models.Model):
    nombre = models.CharField(max_length=100)
    precio = models.PositiveIntegerField()
    historia = HistoricalRecords()
    modulos_disponibles = models.ManyToManyField(Modulo)
    maximo_usuarios = models.PositiveIntegerField()

    def __str__(self):
        return self.nombre

    @staticmethod
    def buscar(id):
        try:
            return Plan.objects.get(id=id)
        except Plan.DoesNotExist:
            return None

    @staticmethod
    def crear_planes_iniciales():
        Modulo.crear_modulos_iniciales()
        if Plan.objects.all().count() == 0:
            plan = Plan.objects.create(nombre="Gratuito", precio=0, maximo_usuarios=5)
            plan.modulos_disponibles = Modulo.objects.filter(
                nombre__in=[
                    "Actividades",
                    "Calendario",
                    "Eventos",
                    "Noticias",
                    "Participantes",
                    "Temas",
                    "Usuarios",
                ]
            )
            plan.save()
            plan = Plan.objects.create(
                nombre="Estandar", precio=25, maximo_usuarios=100
            )
            plan.modulos_disponibles = Modulo.objects.filter(
                nombre__in=[
                    "Actividades",
                    "Calendario",
                    "Eventos",
                    "Noticias",
                    "Participantes",
                    "Reportes",
                    "Temas",
                    "Usuarios",
                ]
            )
            plan.save()
            plan = Plan.objects.create(
                nombre="Empresarial", precio=199, maximo_usuarios=1000
            )
            plan.modulos_disponibles = Modulo.objects.filter(
                nombre__in=[
                    "Actividades",
                    "Calendario",
                    "Eventos",
                    "Noticias",
                    "Participantes",
                    "Reportes",
                    "Temas",
                    "Usuarios",
                ]
            )
            plan.save()

    def obtener_modulos_disponibles(self):
        return [str(modulo) for modulo in self.modulos_disponibles.all()]


def check_schema_name(name):
    if not _is_valid_schema_name(name):
        raise ValidationError("El nombre del esquema es inválido.")


class Empresa(TenantMixin):
    nombre = models.CharField(
        max_length=300, verbose_name="nombre de la empresa", unique=True
    )
    schema_name = models.CharField(
        max_length=63, unique=True, validators=[check_schema_name]
    )
    historia = HistoricalRecords()

    plan = models.ForeignKey(Plan, related_name="empresas")
    tema = models.CharField(max_length=100, choices=CHOICES_TEMA, default="a")
    color = models.CharField(max_length=100, choices=CHOICES_COLOR, default="mint")
    cliente = models.ForeignKey(
        Usuario, verbose_name="cliente de la empresa", related_name="mi_empresa"
    )
    vigencia = models.DateTimeField(
        help_text="Fecha hasta la que se encuentra pago el servicio"
    )

    historia = HistoricalRecords()

    def __str__(self):
        return self.nombre

    @staticmethod
    def buscar(id):
        try:
            return Empresa.objects.get(id=id)
        except Empresa.DoesNotExist:
            return None


class Dominio(DomainMixin):
    historia = HistoricalRecords()


class SolicitudEmpresa(models.Model):
    solicitante = models.ForeignKey(Usuario, related_name="solicitudes")
    nombre = models.CharField(
        max_length=300, unique=True, verbose_name="nombre de la empresa"
    )
    schema_name = models.CharField(
        max_length=63, unique=True, validators=[check_schema_name]
    )
    aceptada = models.NullBooleanField()

    tema = models.CharField(max_length=100, choices=CHOICES_TEMA, default="a")
    color = models.CharField(max_length=100, choices=CHOICES_COLOR, default="mint")
    plan = models.ForeignKey(Plan, verbose_name="plan", related_name="solicitud")
    vigencia = models.DateTimeField(
        help_text="Fecha hasta la que se encuentra pago el servicio"
    )

    historia = HistoricalRecords()

proyectoWWW/apps/empresa/views.py
from django.conf import settings
from django.shortcuts import render, redirect
from django.contrib import messages

from proyectoWWW.utilidades import verificar_cargo, enviar_email

from .forms import *


@verificar_cargo(cargos_permitidos=["Administrador"])
def registrar_empresa(request):
    """
    Función que permite registrar un tenant (empresa) en el sistema
    :param request:
    :return:
    """
    if request.method == "POST":
        form = EmpresaForm(request.POST)
        if form.is_valid():
            from django.db import connection

            empresa = form.save()
            dominio = Dominio(
                domain=("%s%s") % (empresa.schema_name, settings.DOMINIO),
                is_primary=True,
                tenant=empresa,
            )
            dominio.save()
            connection.set_tenant(empresa)
            Usuario.crear_super_admin_cliente(empresa.cliente)
            connection.set_schema_to_public()
            messages.success(request, "La empresa ha sido registrada exitosamente.")
            return redirect("empresa_registrar_empresa")
        else:
            messages.error(
                request,
                "No se pudo registrar la empresa, por favor verificar los datos.",
            )
    else:
        form = EmpresaForm()
    return render(
        request,
        "empresa/empresa_gestion.html",
        {
            "form": form,
            "titulo": "Registro de empresas",
            "dominios": Dominio.objects.exclude(tenant__schema_name="public")
            .select_related("tenant")
            .all(),
            "dominio": settings.DOMINIO,
        },
    )


@verificar_cargo(cargos_permitidos=["Administrador"])
def modificar_empresa(request, empresa_id):
    """
    Función que permite modificar el nombre de empresa del tenant
    :param request:
    :param empresa_id:
    :return:
    """
    empresa = Empresa.buscar(empresa_id)
    if not empresa:
        messages.error(request, "No existe la empresa solicitada.")
        return redirect("empresa_registrar_empresa")
    if empresa.schema_name == "public":
        return redirect("empresa_registrar_empresa")

    if request.method == "POST":
        form = ModificarEmpresaForm(request.POST, instance=empresa)
        if form.is_valid():
            form.save()
            messages.success(request, "La empresa ha sido modificada exitosamente.")
            return redirect("empresa_registrar_empresa")
        else:
            messages.error(
                request,
                "No se pudo modificar la empresa, por favor verificar los datos.",
            )
    else:
        form = ModificarEmpresaForm(instance=empresa)

    return render(
        request,
        "empresa/empresa_gestion.html",
        {
            "form": form,
            "titulo": "Modificación de empresa",
            "dominios": Dominio.objects.exclude(tenant__schema_name="public")
            .select_related("tenant")
            .all(),
            "dominio": settings.DOMINIO,
        },
    )


@verificar_cargo(cargos_permitidos=["Cliente"])
def solicitar_registro_empresa(request, plan_id=1):
    """
        Función que permite registrar una solicitud de creación de tenant (empresa) en el sistema
        :param request:
        :param plan_id: Identificador del plan
        :return:
    """
    plan = Plan.buscar(plan_id)
    if not plan:
        messages.error(request, "No existe el plan buscado")
        return redirect("inicio")

    if request.method == "POST":
        form = SolicitudEmpresaForm(request.POST)
        if form.is_valid():
            solicitud = form.save(commit=False)
            solicitud.solicitante = request.user
            solicitud.plan = plan
            solicitud.save()
            messages.success(request, "La solicitud ha sido registrada exitosamente.")
            return redirect("inicio")
        else:
            messages.error(
                request,
                "No se pudo registrar la solicitud, por favor verificar los datos.",
            )
    else:
        form = SolicitudEmpresaForm()
    return render(
        request,
        "empresa/solicitud_registro_empresa.html",
        {"form": form, "dominio": settings.DOMINIO},
    )


@verificar_cargo(cargos_permitidos=["Administrador"])
def listado_solicitudes(request):
    """
        Función que lista las solicitudes que no hayan recibido respuesta, ya sea aceptada o rechazada
        :param request:
        :return:
    """
    solicitudes = SolicitudEmpresa.objects.filter(aceptada=None)
    return render(
        request, "empresa/solicitud_listado.html", {"solicitudes": solicitudes}
    )


def aceptar_rechazar_solicitud(request, id_solicitud, estado_aprobacion):
    """
    Función que permite aceptar o rechazar una solicitud y crear una empresa a partir de ella

    :param request:
    :param id_solicitud:
    :param estado_aprobacion:
    :return:
    """

    try:
        solicitud = SolicitudEmpresa.objects.get(id=id_solicitud)
    except Exception:
        messages.error(request, "No existe la solicitud")
        return redirect("empresa_listado_solicitudes")

    if solicitud.aceptada != None:
        messages.error(request, "No es posible modificar la solicitud")
        return redirect("empresa_listado_solicitudes")

    if estado_aprobacion == "0":
        solicitud.aceptada = False
        messages.success(request, "Solicitud rechazada")
        solicitud.save()
    elif estado_aprobacion == "1":
        form = RegistrarEmpresaSolicitudForm(
            {
                "nombre": solicitud.nombre,
                "schema_name": solicitud.schema_name,
                "tema": solicitud.tema,
                "color": solicitud.color,
                "vigencia": solicitud.vigencia,
            }
        )
        if form.is_valid():
            from django.db import connection

            empresa = form.save(commit=False)
            empresa.cliente = solicitud.solicitante
            empresa.plan = solicitud.plan
            empresa.save()
            dominio = Dominio(
                domain=("%s%s") % (empresa.schema_name, settings.DOMINIO),
                is_primary=True,
                tenant=empresa,
            )
            dominio.save()
            connection.set_tenant(empresa)
            Usuario.crear_super_admin_cliente(empresa.cliente)

            cliente = empresa.cliente
            datos_email = {
                "subject": "Solicitud de empresa aceptada",
                "body": "Su usuario es: admin, su contraseña es: %s-%s, su dominio es: %s%s"
                % (cliente.cedula, cliente.first_name, empresa.schema_name, settings.DOMINIO),
                "to": [cliente.email],
                "mensaje_error": "Error al enviar correo",
            }
            enviar_email(request=None, **datos_email)
            solicitud.aceptada = True
            messages.success(request, "Solicitud aceptada")
            solicitud.save()
        else:
            solicitud.aceptada = None
            print(form.errors)
            messages.error(
                request,
                "No se ha podido aceptar la solicitud, por favor verificar los datos.",
            )
            solicitud.save()

    return redirect("empresa_listado_solicitudes")


@verificar_cargo(cargos_permitidos=["Cliente"])
def gestionar_empresas(request, empresa_id=None):
    """
    Función que permite gestionar sus emrepesas a un cliente
    :param request:
    :param empresa_id:
    :return:
    """
    form = None
    empresa = Empresa.buscar(empresa_id)
    if empresa:
        form = ModificarEmpresaClienteForm(instance=empresa)

    if request.method == "POST":
        form = ModificarEmpresaClienteForm(request.POST, instance=empresa)
        if form.is_valid():
            form.save()
            messages.success(request, "La empresa ha sido modificada exitosamente.")
            return redirect("empresa_gestionar_empresas_cliente")
        else:
            messages.error(
                request,
                "No se pudo modificar la empresa, por favor verificar los datos.",
            )

    return render(
        request,
        "empresa/empresa_gestion_cliente.html",
        {
            "form": form,
            "titulo": "Gestión de empresa",
            "dominios": Dominio.objects.filter(tenant__cliente=request.user)
            .select_related("tenant")
            .all(),
            "dominio": settings.DOMINIO,
        },
    )


@verificar_cargo(cargos_permitidos=["Cliente"])
def obtener_copia_seguridad(request, empresa_id):
    """
    Función que permite obtener un backup de los datos de la empresa a un cliente
    :param request:
    :param empresa_id:
    :return:
    """
    import sys
    from io import StringIO

    from django.http import HttpResponse
    from django.core.management import call_command
    from django.db import connection

    from apps.empresa.models import Empresa

    backup_empresa = StringIO()

    try:
        empresa = Empresa.buscar(empresa_id)
        if empresa:
            connection.set_tenant(empresa)
            sysout = sys.stdout
            sys.stdout = backup_empresa
            call_command(
                "dumpdata", indent=4, exclude=["auth", "sessions", "contenttypes"]
            )
            sys.stdout = sysout
            connection.set_schema_to_public()
        else:
            messages.error(
                request, "Error al generar el archivo, por favor intente nuevamente."
            )
            return redirect("empresa_gestionar_empresas_cliente")

    except Exception:
        messages.error(
            request, "Error al generar el archivo, por favor intente nuevamente."
        )
        return redirect("empresa_gestionar_empresas_cliente")

    backup_empresa.seek(0)
    response = HttpResponse(backup_empresa, content_type="application/text")
    backup_empresa.close()
    response["Content-Disposition"] = (

proyectoWWW/apps/empresa/templates/empresa/empresa_gestion.html
{% extends "base_tablas.html" %}
{% load bootstrap3 %}
{% load staticfiles %}

{% block titulo %}
    {{ titulo }}
{% endblock titulo %}

{% block titulo_pagina %}
    {{ titulo }}
{% endblock titulo_pagina %}

{% block titulo_panel %}
    {{ titulo }}
{% endblock titulo_panel %}

{% block miga_pan %}
    <li class="active">{% if "registrar" in request.path %} Registro {% else %} Modificar {% endif %}</li>
{% endblock miga_pan %}

{% block contenido %}
    <div class="row">
        <div class="col-sm-4 col-md-4">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <div class="panel-control">

                    </div>
                    <h3 class="panel-title">{{ titulo }}</h3>
                </div>
                <div class="panel-body">
                    <form class="form-vertical" method="POST">{% csrf_token %}
                        {% bootstrap_form form layout="vertical" %}
                        <div class="col-xs-12" align="right">
                            <a href="{% url 'empresa_registrar_empresa' %}" class="btn btn-dark">Volver </a>
                            <button type="submit" class="btn btn-primary">
                                Guardar
                            </button>
                        </div>
                    </form>
                </div>
                <div class="panel-footer">

                </div>
            </div>
        </div>
        <div class="col-sm-8 col-md-8">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <div class="panel-control">

                    </div>
                    <h3 class="panel-title">Listado de empresas actuales</h3>
                </div>
                <div class="panel-body">
                    <div class="table-responsive">
                        <table class="table table-striped table-bordered tabla-responsive">
                            <thead>
                                <tr>
                                    <th>Nombre</th>
                                    <th>Dirección</th>
                                    <th>Cliente</th>
                                    <th>Opciones</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for dominio in dominios %}
                                    <tr>
                                        <td>
                                            {{ dominio.tenant.nombre }}
                                        </td>
                                        <td>
                                            {{ dominio.domain }}
                                        </td>
                                        <td>
                                            {{ dominio.tenant.cliente }}
                                        </td>
                                        <td>
                                            <div class="btn-group btn-group-sm">
                                                <div class="dropdown">
                                                    <button class="btn btn-sm btn-primary btn-active-primary dropdown-toggle" data-toggle="dropdown" type="button">
                                                        Opciones <i class="ti-angle-down"></i>
                                                    </button>
                                                    <ul class="dropdown-menu dropdown-menu-right">
                                                        <li><a href="{% url 'empresa_modificar_empresa' dominio.tenant.id %}">Modificar</a></li>

                                                    </ul>
                                                </div>
					                        </div>
                                        </td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
                <div class="panel-footer">

                </div>
            </div>
        </div>
    </div>
{% endblock contenido %}

{% block  js %}
    {{ block.super }}
    <script>
        dominio = '{{ dominio|safe }}';
        $id_schema_name = $('#id_schema_name');
        $help_text = $id_schema_name.next();
        if ($help_text.html() !== 'Esta será su direccion: midireccion'+dominio){
            $help_text = $help_text.next();
        }

        $id_schema_name.on('change keydown paste input',function () {
            direccion = $id_schema_name.val();

            $help_text.html('Esta será su direccion: '+direccion+dominio);
        });
        $id_schema_name.trigger('change');

    </script>

    <script src="{% static 'plugins/bootstrap-datepicker/bootstrap-datepicker.min.js' %}"></script>
    <script src="{% static 'plugins/bootstrap-datepicker/locales/bootstrap-datepicker.es.min.js' %}"></script>
    <script>
        $('.component-date').datepicker({
            language: 'es',
            autoclose: true,
            format: 'yyyy-mm-dd',
            orientation: "bottom",
        });
    </script>
{% endblock %}

proyectoWWW/apps/empresa/templates/empresa/empresa_gestion_cliente.html
{% extends "base_tablas.html" %}
{% load bootstrap3 %}
{% load staticfiles %}

{% block titulo %}
    {{ titulo }}
{% endblock titulo %}

{% block titulo_pagina %}
    {{ titulo }}
{% endblock titulo_pagina %}

{% block titulo_panel %}
    {{ titulo }}
{% endblock titulo_panel %}

{% block miga_pan %}
    <li class="active">Gestionar</li>
{% endblock miga_pan %}

{% block contenido %}
    <div class="row">
        {% if form %}
            <div class="col-sm-4 col-md-4">
                <div class="panel panel-primary">
                    <div class="panel-heading">
                        <div class="panel-control">

                        </div>
                        <h3 class="panel-title">{{ titulo }}</h3>
                    </div>
                    <div class="panel-body">
                        <form class="form-vertical" method="POST">{% csrf_token %}
                            {% bootstrap_form form layout="vertical" %}
                            <div class="col-xs-12" align="right">
                                <a href="{% url 'empresa_gestionar_empresas_cliente' %}" class="btn btn-dark">Volver </a>
                                <button type="submit" class="btn btn-primary">
                                    Guardar
                                </button>
                            </div>
                        </form>
                    </div>
                    <div class="panel-footer">

                    </div>
                </div>
            </div>
        {% endif %}
        <div class="{% if form %}col-sm-8 col-md-8{% else %}col-sm-12 col-md-12{% endif %}">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <div class="panel-control">

                    </div>
                    <h3 class="panel-title">Listado de empresas actuales</h3>
                </div>
                <div class="panel-body">
                    <div class="table-responsive">
                        <table class="table table-striped table-bordered tabla-responsive">
                            <thead>
                                <tr>
                                    <th>Nombre</th>
                                    <th>Dirección</th>
                                    <th>Opciones</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for dominio in dominios %}
                                    <tr>
                                        <td>
                                            {{ dominio.tenant.nombre }}
                                        </td>
                                        <td>
                                            {{ dominio.domain }}
                                        </td>
                                        <td>
                                            <div class="btn-group btn-group-sm">
                                                <div class="dropdown">
                                                    <button class="btn btn-sm btn-primary btn-active-primary dropdown-toggle" data-toggle="dropdown" type="button">
                                                        Opciones <i class="ti-angle-down"></i>
                                                    </button>
                                                    <ul class="dropdown-menu dropdown-menu-right">
                                                        <li><a href="{% url 'empresa_modificar_empresa_cliente' dominio.tenant.id %}">Modificar</a></li>
                                                        <li><a href="{% url 'empresa_copia_seguridad_empresa' dominio.tenant.id %}">Descargar copia de seguridad</a></li>
                                                    </ul>
                                                </div>
					                        </div>
                                        </td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock contenido %}

{% block  js %}
    {{ block.super }}
    {% if form %}
        <script>
            static = {% static '' %};
            function obtener_enlace_tema(){
                return static+"css/themes/type-"+$("#id_tema").val()+"/theme-"+$("#id_color").val()+".min.css"
            }


            $('#id_tema, #id_color').on('change',function () {
                $('#tema-aplicacion').attr("href",obtener_enlace_tema())
            });
            $('#tema-aplicacion').attr("href",obtener_enlace_tema())
        </script>

        <script src="{% static 'plugins/bootstrap-datepicker/bootstrap-datepicker.min.js' %}"></script>
        <script src="{% static 'plugins/bootstrap-datepicker/locales/bootstrap-datepicker.es.min.js' %}"></script>
        <script>
            $('.component-date').datepicker({
                language: 'es',
                autoclose: true,
                format: 'yyyy-mm-dd',
                orientation: "bottom",
            });
        </script>
    {% endif %}

{% endblock %}

proyectoWWW/apps/empresa/templates/empresa/solicitud_registro_empresa.html
{% extends "base_tablas.html" %}
{% load bootstrap3 %}
{% load staticfiles %}

{% block titulo %}
    Solicitar creación de empresa
{% endblock titulo %}

{% block titulo_pagina %}
    Solicitar creación de empresa
{% endblock titulo_pagina %}

{% block titulo_panel %}
    Solicitar creación de empresa
{% endblock titulo_panel %}

{% block miga_pan %}
    <li class="active">Solicitar creación de empresa</li>
{% endblock miga_pan %}

{% block contenido %}
    <div class="row">
        <div class="col-sm-4 col-md-4">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <div class="panel-control">

                    </div>
                    <h3 class="panel-title">Solicitar creación de empresa</h3>
                </div>
                <div class="panel-body">
                    <form class="form-vertical" method="POST">{% csrf_token %}
                        {% bootstrap_form form layout="vertical" %}
                        <div class="col-xs-12" align="right">
                            <a href="{% url 'inicio' %}" class="btn btn-dark">Volver </a>
                            <button type="submit" class="btn btn-primary">
                                Guardar
                            </button>
                        </div>
                    </form>
                </div>
                <div class="panel-footer">

                </div>
            </div>
        </div>
    </div>
{% endblock contenido %}

{% block  js %}
    {{ block.super }}
    <script>
        dominio = '{{ dominio|safe }}';
        $id_schema_name = $('#id_schema_name');
        $help_text = $id_schema_name.next();
        console.log($help_text.html());
        console.log(dominio);
        if ($help_text.html() !== 'Esta será su direccion: midireccion'+dominio){
            $help_text = $help_text.next();
        }

        $id_schema_name.on('change keydown paste input',function () {
            direccion = $id_schema_name.val();

            $help_text.html('Esta será su direccion: '+direccion+dominio);
        });
        $id_schema_name.trigger('change');

    </script>

    <script>
        static = {% static '' %};
        function obtener_enlace_tema(){
            return static+"css/themes/type-"+$("#id_tema").val()+"/theme-"+$("#id_color").val()+".min.css"
        }


        $('#id_tema, #id_color').on('change',function () {
            $('#tema-aplicacion').attr("href",obtener_enlace_tema())
        })
    </script>

    <script src="{% static 'plugins/bootstrap-datepicker/bootstrap-datepicker.min.js' %}"></script>
    <script src="{% static 'plugins/bootstrap-datepicker/locales/bootstrap-datepicker.es.min.js' %}"></script>
    <script>
        $('.component-date').datepicker({
            language: 'es',
            autoclose: true,
            format: 'yyyy-mm-dd',
            orientation: "bottom",
        });
    </script>
{% endblock %}